<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>

<?php if($_product['make_simple_as_group'] == '1'){ ?>
<?php //echo $_product['foundation_shades']; ?>
<?php if(!empty($_product['key_of_group'])){?>
<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();  
$prodColl = $objectManager->create('Magento\Catalog\Model\ResourceModel\Product\Collection');
$collection = $prodColl->addAttributeToSelect('*')
                       ->addAttributeToFilter('key_of_group', ['eq'=> $_product['key_of_group']])
                       ->load();
  foreach ($collection as  $item) {
$productRepository = $objectManager->get('\Magento\Catalog\Model\ProductRepository');
$product = $productRepository->get($item->getSku());
//echo $product['foundation_shades']; 
$resource = $objectManager->get('Magento\Framework\App\ResourceConnection');
$connection = $resource->getConnection();
$tableName = $resource->getTableName('eav_attribute_option_swatch');
$sql = "Select * FROM " . $tableName . " WHERE  option_id= ".$product['foundation_shades'];

$result = $connection->fetchAll($sql); 
 if($product['foundation_shades'] == $_product['foundation_shades']){

  $active ="selected" ;
 }

//$swatchHelper = $objectManager->get('Magento\Swatches\Helper\Data');
 //$hashcodeData = $swatchHelper->getSwatchesByOptionsId(11);
 //($hashcodeData);

 //echo  $hashcodeData[$product['foundation_shades']]['value'];
 $attr = $product->getResource()->getAttribute('foundation_shades');
 echo '<ul class="costom-color-swatch">';
 if ($attr->usesSource()) {
      echo '<li class="swatch-option '.$active.'" style="background: '.$result[0]['value'].' no-repeat center;
    background-size: initial;"> <a href=" '.$product->getProductUrl().'">'. $optionText = $attr->getSource()->getOptionText($product['foundation_shades']) .'</li>';

      //$attr->getSource()->getOptionSwatch($product['foundation_shades']);
 }
echo '</ul>';
}                     

?>

<?php } } ?>


<?php if(!empty($_product['shipping_info'])){?>
<div class="product attribute overview">
                          <h5>Shipping</h5>
                          <p><?php echo $_product['shipping_info']; ?>.</p>
                        </div>
						
<?php } ?>						
<?php $buttonTitle = __('Add to Bag'); ?>
<?php if ($_product->isSaleable()): ?>
<div class="box-tocart">
    <div class="fieldset">
        <?php if ($block->shouldRenderQuantity()): ?>
        <?php if($_product['show_qty'] != '1'){ ?>
		<div class="field qty qty-col">
            <label class="label" for="qty"><span><?= /* @escapeNotVerified */ __('Select a Quantity') ?></span></label>
			
			
            <div class="qty-container">
              <div class="qty-input">
			  <button type="button" class="btnMin">-</button>
                <input type="number"
                       name="qty"
                       id="qty"
                       value="<?= /* @escapeNotVerified */ $block->getProductDefaultQty() * 1 ?>"
                       title="<?= /* @escapeNotVerified */ __('Qty') ?>"
                       class="input-text qty"
                       data-validate="<?= $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                       />
				<button type="button" class="btnAdd">+</button>
            </div>
			 </div>
			 
			
			 
        </div>
		<?php }?>
        <?php endif; ?>
        <div class="actions">
            <button type="submit"
                    title="<?= /* @escapeNotVerified */ $buttonTitle ?>"
                    class="action primary tocart"
                    id="product-addtocart-button">
                <span><?= /* @escapeNotVerified */ $buttonTitle ?></span>
            </button>
            <?= $block->getChildHtml('', true) ?>
        </div>
    </div>
</div>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/js/validate-product": {}
        }
    }
</script>

<script type="text/javascript"> 
require(["jquery"], function(jQuery){
  jQuery(document).ready(function(){
    jQuery('.btnAdd').click(function() {
		//alert('+++')
      var oldVal = jQuery(this).parent().find("input").val();
      if ( parseFloat(oldVal) >= 1 ) {
        var newVal = parseFloat(oldVal) + 1;
        jQuery(this).parent().find("input").val(newVal);
      }
    });

    jQuery('.btnMin').click(function() {
      var oldVal = jQuery(this).parent().find("input").val();
      if ( parseFloat(oldVal) >= 2 ) {
        var newVal = parseFloat(oldVal) - 1;
        jQuery(this).parent().find("input").val(newVal);
      }
    });
  });
  });
</script>