<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /** @var $block \Magento\Catalog\Block\Product\AbstractProduct */ ?>
<?= $block->getReviewsSummaryHtml($block->getProduct(), false, true) ?>

<?php  $_product = $block->getProduct() ; if($_product['bogo']=='1'){
echo '<span class="list-bogo">BOGO</span>' ;
} ?>
