
                    <div class="content-menu">
                      <ul class="header-top-menu">
                          <li><a href="javascript:void(0);">Ask Jerome</a></li>
                          <li><a href="javascript:void(0);">Community Reviews</a></li>
                          <li><a href="javascript:void(0);">Contact Us</a></li>
                      </ul>
                    </div>
					
                    <div class="block block-search header-search">
                      <div class="block block-content form-group">
                          <input type="text" class="form-control" placeholder="Search the website">
                          <button class="search-btn">
                            <!-- <i class="fa fa-search" aria-hidden="true"></i> -->
                            <img src="<?php echo $this->getMediaurl()?>themeimage/search-icon.png" alt="">
                          </button>
                      </div>    
                    </div>
					
					<div class="header-bag">
                      <div class="sign-col">
                          <a href="javascript:void(0);" class="singin-link">
                              <i class="fa"><img src="<?php echo $this->getMediaurl()?>themeimage/user.png" alt=""></i>
                              <span class="">Sign In</span>
                          </a> 
                      </div>
                      <div class="minicart-wrapper bag-col">
                          <a href="javascript:void(0);" class="cart-link">
                              <i class="fa"><img src="<?php echo $this->getMediaurl()?>themeimage/shopping_bag.png" alt=""></i>
                              <span>Bag</span>
                              <span class="cart-circle">0</span>
                          </a>
                      </div>
                    </div>
					  <?php //echo $this->getChildHtml('minicart') ?>
					  <?php //echo $this->getChildHtml('topsearch') ?>
                    
    
		
	
		
					
		