<?php
$randid =$this->getRandid();
$products  = $this->getAllproducts($randid['increment_id']);

if(!empty($randid)){
if(!empty($products)){	
	
?>

<?php if( !empty($products['items'][0]['name']) ){?>

<div class="advertise-bx">
<button class="close-add"><i class="fa fa-times"></i></button>
  <a href="<?php  echo $products['items'][0]['producturl']?>" > 
   <div class="advertise-img">
   <?php if(!empty($products['items'][0]['productImage'])){ ?>
   <img src=" <?php  echo  $this->getMedia().'pub/media/catalog/product'.$products['items'][0]['productImage']?>" alt="" class="img-fluid">  
   <?php }else{  ?>
   <img src=" <?php  echo  $this->getMedia().'pub/media/themeimage/placehoder.jpg' ;?>" alt="" class="img-fluid">  
  
   <?php } ?>

   </div>
   <div class="advertise-info">
   <p><?php  echo $products['order_name']?> from <?php  echo $products['region']?> has purchased a</p>
   <h6><?php  echo $products['items'][0]['name']?></h6>
   <?php 
  
 $date1 = date('m/d/Y h:i:s', time());
 $date2 = $products['order_date'];
$seconds = strtotime($date1) - strtotime($date2);
$hours = $seconds / 60 /  60;
  ?>
   <span>about <?php echo round($hours) ;?> hours ago</span>
   </div> 
   </a>
  </div>
  

<?php }}}?> 




<?php 
/*echo $randid['increment_id'] ;
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$order = $objectManager->create('Magento\Sales\Model\Order')->loadByIncrementId(000000153);
    
$orderItems = $order->getAllItems();
	
foreach($orderItems as $item)
{
	
echo "SKU: " . addslashes($item->getSku()).'<br>';
       //echo "ID: " . addslashes($item->getId());
	   $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$productId = $objectManager->get('Magento\Catalog\Model\Product')->getIdBySku($item->getSku());
print_r($productId);
}*/

?>
<script type="text/javascript">
require([ 'jquery'], function($){

$(document).ready(function(){
	
	$(".close-add").on("click", function(){
		$(".promotion-box").hide();
	});

	
	
});
	
});
</script>
