<?php
$randid =$this->getRandid();
$products  = $this->getAllproducts($randid['increment_id']);
//echo"<pre>";print_r($products);die;

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $product1 = $objectManager->create('Magento\ConfigurableProduct\Model\ResourceModel\Product\Type\Configurable')->getParentIdsByChild($products['items'][0]['product_id']);
     if(isset($product[0])){
         //this is parent product id..
         echo $product1[0];
		  //echo "<pre>";print_r($product->getData());
    }

if(!empty($product1[0])){
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$prdoduct = $objectManager->get('Magento\Catalog\Model\Product')->load($product1[0]);
$store = $objectManager->get('Magento\Store\Model\StoreManagerInterface')->getStore();
 
$productImageUrl = $store->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA) . 'catalog/product' . $prdoduct->getImage();
echo $productUrl  = $product->getProductUrl();
}	
//echo $products['items'][0]['product_id'] ;
?>

<?php if( !empty($products['items'][0]['name']) ){?>

<div class="advertise-bx">
<button class="close-add"><i class="fa fa-times"></i></button>
  <a href="<?php  echo $products['items'][0]['producturl']?>" > 
   <div class="advertise-img">
   <?php if(!empty($products['items'][0]['productImage'])){ ?>
   <img src=" <?php  echo  $this->getMedia().'catalog/product'.$products['items'][0]['productImage']?>" alt="" class="img-fluid">  
   <?php }else{  ?>
   <img src=" <?php  echo  $this->getMedia().'themeimage/placehoder.jpg' ;?>" alt="" class="img-fluid">  
  
   <?php } ?>

   </div>
   <div class="advertise-info">
   <p><?php  echo $products['order_name']?> from <?php  echo $products['region']?> has purchased a</p>
   <h6><?php  echo $products['items'][0]['name']?></h6>
   <?php 
  
 $date1 = date('m/d/Y h:i:s', time());
 $date2 = $products['order_date'];
$seconds = strtotime($date1) - strtotime($date2);
$hours = $seconds / 60 /  60;
  ?>
   <span>about <?php echo round($hours) ;?> hours ago</span>
   </div> 
   </a>
  </div>
  
<?php }?> 