<div class="customer-review " data-aos="fade-up" data-aos-offset="150" data-aos-easing="ease-in-sine">
<div class="row write-review-form">
<div class="col-12 title-col">
<div class="form-group">
<h4>Write a Review</h4>
</div>
</div>
<form class="form" action="<?php echo $this->getUrl('shopall/index/writereview');?>" id="writereview-form" method="post"  data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
      data-mage-init='{"validation":{}}'>
<div class="col-12 store-col">



<div class="form-group"><label for="">Store <span>*</span></label>
<div class="rating-star"><i class="fa fa-star-o"></i> <i class="fa fa-star-o"></i> <i class="fa fa-star-o"></i> <i class="fa fa-star-o"></i> <i class="fa fa-star-o"></i></div>
</div>
</div>



<div class="col-md-6 col-12 name-col">
<div class="form-group"><label for="">First Name <span>*</span></label> 
<input class="form-control" type="text" name="first_name"  value="" data-validate="{required:true}"/>
</div>
</div>
<div class="col-12 review-comment-col">
<div class="form-group"><label for="">Review <span>*</span></label> <textarea id="" class="form-control" name="review" value="" rows="10" data-validate="{required:true}"></textarea></div>
</div>
<div class="col-12 age-radio-col">
<div class="form-group"><label for="">Age</label>
<div class="custom-control custom-radio"><input id="customRadio1" name="age" value="65+" class="custom-control-input  required-entry" name="customRadio" type="radio" /> <label class="custom-control-label" for="customRadio1">65+</label></div>
<div class="custom-control custom-radio"><input id="customRadio2"  name="age" value="55-64" class="custom-control-input  required-entry" name="customRadio" type="radio" /> <label class="custom-control-label" for="customRadio2">55-64</label></div>
<div class="custom-control custom-radio"><input id="customRadio3" name="age" value="45-54" class="custom-control-input  required-entry" name="customRadio" type="radio" /> <label class="custom-control-label" for="customRadio3">45-54</label></div>
<div class="custom-control custom-radio"><input id="customRadio4" name="age" value="35-44" class="custom-control-input  required-entry" name="customRadio" type="radio" /> <label class="custom-control-label" for="customRadio4">35-44</label></div>
<div class="custom-control custom-radio"><input id="customRadio5" name="age" value="25-34" class="custom-control-input required-entry" name="customRadio" type="radio" /> <label class="custom-control-label" for="customRadio5">25-34</label></div>
<div class="custom-control custom-radio"><input id="customRadio6" name="age" value="18-24" class="custom-control-input  required-entry" name="customRadio" type="radio" /> <label class="custom-control-label" for="customRadio6">18-24</label></div>
</div>
</div>
<div class="col-12 skin-radio-col">
<div class="form-group"><label for="">Skin Type</label>
<div class="custom-control custom-radio"><input id="customRadio7" name ="skin" value="Normal" class="custom-control-input  required-entry" name="customRadio" type="radio" /> <label class="custom-control-label" for="customRadio7">Normal</label></div>
<div class="custom-control custom-radio"><input id="customRadio8" name ="skin" value="Dry" class="custom-control-input  required-entry" name="customRadio" type="radio" /> <label class="custom-control-label" for="customRadio8">Dry</label></div>
<div class="custom-control custom-radio"><input id="customRadio9" name ="skin" value="Oily" class="custom-control-input  required-entry" name="customRadio" type="radio" /> <label class="custom-control-label" for="customRadio9">Oily</label></div>
<div class="custom-control custom-radio"><input id="customRadio10" name ="skin" value="Combination" class="custom-control-input  required-entry" name="customRadio" type="radio" /> <label class="custom-control-label" for="customRadio10">Combination</label></div>
<div class="custom-control custom-radio"><input id="customRadio11" name ="skin" value="Lines" class="custom-control-input  required-entry" name="customRadio" type="radio" /> <label class="custom-control-label" for="customRadio11">Lines</label></div>
<div class="custom-control custom-radio"><input id="customRadio12" name ="skin" value="Acne Prone" class="custom-control-input  required-entry" name="customRadio" type="radio" /> <label class="custom-control-label" for="customRadio12">Acne Prone</label></div>
</div>
</div>
<div class="col-12 btn-col">
<div class="form-group"><button class="btn btn-primary done-btn" type="button">Done</button></div>
</div>
</form>

</div>
</div>

<script type="text/x-magento-init">
    {
        "#writereview-form": {
            "validation": {}
        }
    }
</script>