<?php
$ifram=$this->getIfram();

echo "<pre>";print_r($ifram);


$objectManager =  \Magento\Framework\App\ObjectManager::getInstance();
$orderDatamodel = $objectManager->get('Magento\Sales\Model\Order')->getCollection()->getLastItem();
$orderId   =   $orderDatamodel->getId();
$order = $objectManager->create('\Magento\Sales\Model\Order')->load($orderId);
$orderItems = $order->getAllItems();
$order->getCreatedAt();
foreach ($orderItems as $item) {
   echo $product_name=   $item->getName();
   echo $product_id=   $item->getId();
}
?>