<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php 
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$category = $objectManager->get('Magento\Framework\Registry')->registry('current_category');//get current category
if(!empty($category)){
if($category->getId()=='3'){?>
<span id="shopallproduct">
<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('shopall')->toHtml(); ?>	
</span>			
<?php } else { ?>

<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty"><div><?= /* @escapeNotVerified */ __('We can\'t find products matching the selection.') ?></div></div>
<?php else: ?>
    <?php //$block->getToolbarHtml() ?>
    <?= $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $image = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $image = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    <div class="category-lissting airbrush-listing row-col products wrapper <?= /* @escapeNotVerified */ $viewMode ?> products-<?= /* @escapeNotVerified */ $viewMode ?>">
        <?php $iterator = 1; ?>
       <div class="category-row category-airbrush">
       <div class="row">
							  <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product): ?>
               <!-- <?= /* @escapeNotVerified */ ($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>-->
                
				<div class="col-lg-3 col-md-4 col-12" data-aos="fade-up" data-aos-offset="150"  data-aos-easing="ease-in-sine">
				<div class="category-item">
				
				<!--<div class="product-item-info" data-container="product-<?= /* @escapeNotVerified */ $viewMode ?>"></div>-->
                    <?php
                    $productImage = $block->getImage($_product, $image);
                    if ($pos != null) {
                        $position = ' style="left:' . $productImage->getWidth() . 'px;'
                            . 'top:' . $productImage->getHeight() . 'px;"';
                    }
                    ?>
                    <?php // Product Image ?>
                    <a href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                       <figure> <?= $productImage->toHtml() ?></figure>
                    </a>
		
                <div id="quickview-<?php echo $_product->getId();?>" class="bss-bt-quickview">
				<a class="bss-quickview" data-quickview-url="<?php echo $this->getUrl('');?>/bss_quickview/catalog_product/view/id/<?php echo $_product->getId();?>" href="javascript:void(0);"><span>Quick View </span></a>
				</div>		
                    <div class="seller-info">
                       <div class="star-col">
			<?= $this->helper('Yotpo\Yotpo\Helper\Data')->showBottomline($block,$_product) ?>
                      <?= $block->getReviewsSummaryHtml($_product, $templateType) ?>
                      </div>
                        <?php
                            $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                        ?>
                       
                        
						<div class="seller-name-col">
                                            
                            <a class="title-name"
                               href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>">
                                <?= /* @escapeNotVerified */ $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                            </a>
							<?= $this->helper('Yotpo\Yotpo\Helper\Data')->showBottomline($block, $_product) ?>
							<p> 
					    <?php 
							$short_description = $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description');
	                      $short_description = preg_replace("/<img[^>]+\>/i", "", $short_description); 
                         if (strlen($short_description) > 100){
                        echo strip_tags(substr($short_description, 0, strpos($short_description,' ',100))).'...';
                           } 
                       else { 
                      echo strip_tags($short_description); 
                           }
                           ?>
							</p>
                           <span class="price-span"><?= /* @escapeNotVerified */ $block->getProductPrice($_product) ?>
						   <?php  if($_product['bogo']=='1'){
								echo '<span class="list-bogo">BOGO</span>' ;
								
							} ?>
                        </span>
                      </div>
						
                        
                        <?php  $block->getProductDetailsHtml($_product) ?>

                          <!-- <div class="product-item-inner">
                         <div class="product actions product-item-actions"<?= strpos($pos, $viewMode . '-actions') ? $position : '' ?>>
                                <div class="actions-primary"<?= strpos($pos, $viewMode . '-primary') ? $position : '' ?>>
                                    <?php if ($_product->isSaleable()): ?>
                                        <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                        <form data-role="tocart-form" data-product-sku="<?= $block->escapeHtml($_product->getSku()) ?>" action="<?= /* @NoEscape */ $postParams['action'] ?>" method="post">
                                            <input type="hidden" name="product" value="<?= /* @escapeNotVerified */ $postParams['data']['product'] ?>">
                                            <input type="hidden" name="<?= /* @escapeNotVerified */ Action::PARAM_NAME_URL_ENCODED ?>" value="<?= /* @escapeNotVerified */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                            <?= $block->getBlockHtml('formkey') ?>
                                            <button type="submit"
                                                    title="<?= $block->escapeHtml(__('Add to Cart')) ?>"
                                                    class="action tocart primary">
                                                <span><?= /* @escapeNotVerified */ __('Add to Cart') ?></span>
                                            </button>
                                        </form>
                                    <?php else: ?>
                                        <?php if ($_product->isAvailable()): ?>
                                            <div class="stock available"><span><?= /* @escapeNotVerified */ __('In stock') ?></span></div>
                                        <?php else: ?>
                                            <div class="stock unavailable"><span><?= /* @escapeNotVerified */ __('Out of stock') ?></span></div>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                </div>
                                <div data-role="add-to-links" class="actions-secondary"<?= strpos($pos, $viewMode . '-secondary') ? $position : '' ?>>
                                    <?php if ($addToBlock = $block->getChildBlock('addto')): ?>
                                        <?= $addToBlock->setProduct($_product)->getChildHtml() ?>
                                    <?php endif; ?>
                                </div>
                            </div>
                            <?php if ($showDescription):?>
                                <div class="product description product-item-description">
                                    <?= /* @escapeNotVerified */ $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                    <a href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>" title="<?= /* @escapeNotVerified */ $_productNameStripped ?>"
                                       class="action more"><?= /* @escapeNotVerified */ __('Learn More') ?></a>
                                </div>
                            <?php endif; ?>
                        </div>-->
                    </div>
                
				</div>
				</div>
                <!--<?= ($iterator == count($_productCollection)+1) ? '</li>' : '' ?> -->
            <?php endforeach; ?>
        </div>
		</div>
    </div>
	<?php $block->getToolbarHtml() ?>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {
                    "product_sku": "<?= /* @NoEscape */ $_product->getSku() ?>"
                }
            }
        }
        </script>
    <?php endif; ?>
<?php endif; ?>

<script>
    require([
        'jquery'
    ], function ($) {
        $(document).ready(function(){
            // move hero banner to top of the page
          
            $('.breadcrumbs').detach().insertAfter('.category-view');		
			 $('.page-title-wrapper').detach().insertAfter('.breadcrumbs');	
			
		})
    })
</script>

<?php } ?>

<?php } else {?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty"><div><?= /* @escapeNotVerified */ __('We can\'t find products matching the selection.') ?></div></div>
<?php else: ?>
    <?php //$block->getToolbarHtml() ?>
    <?= $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $image = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $image = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    <div class="category-lissting airbrush-listing row-col products wrapper <?= /* @escapeNotVerified */ $viewMode ?> products-<?= /* @escapeNotVerified */ $viewMode ?>">
        <?php $iterator = 1; ?>
       <div class="category-row category-airbrush">
       <div class="row">
							  <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product): ?>
               <!-- <?= /* @escapeNotVerified */ ($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>-->
                
				<div class="col-lg-3 col-md-4 col-12" data-aos="fade-up" data-aos-offset="150"  data-aos-easing="ease-in-sine">
				<div class="category-item">
				
				<!--<div class="product-item-info" data-container="product-<?= /* @escapeNotVerified */ $viewMode ?>"></div>-->
                    <?php
                    $productImage = $block->getImage($_product, $image);
                    if ($pos != null) {
                        $position = ' style="left:' . $productImage->getWidth() . 'px;'
                            . 'top:' . $productImage->getHeight() . 'px;"';
                    }
                    ?>
                    <?php // Product Image ?>
                    <a href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                       <figure> <?= $productImage->toHtml() ?></figure>
                    </a>
					
			<div id="quickview-<?php echo $_product->getId();?>" class="bss-bt-quickview">
				<a class="bss-quickview" data-quickview-url="<?php echo $this->getUrl('');?>/bss_quickview/catalog_product/view/id/<?php echo $_product->getId();?>" href="javascript:void(0);"><span>Quick View </span></a>
				</div>
				
					
                    <div class="seller-info">
                       <div class="star-col">
                      <?= $block->getReviewsSummaryHtml($_product, $templateType) ?>
                      </div>
                        <?php
                            $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                        ?>
                       
                        
						<div class="seller-name-col">
                                            
                            <a class="title-name"
                               href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>">
                                <?= /* @escapeNotVerified */ $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                            </a>
						<p> 
					    <?php 
							$short_description = $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description');
	                      $short_description = preg_replace("/<img[^>]+\>/i", "", $short_description); 
                         if (strlen($short_description) > 100){
                        echo strip_tags(substr($short_description, 0, strpos($short_description,' ',100))).'...';
                           } 
                       else { 
                      echo strip_tags($short_description); 
                           }
                           ?>
					</p>
                           <span class="price-span"><?= /* @escapeNotVerified */ $block->getProductPrice($_product) ?>
						    <?php  if($_product['bogo']=='1'){
								echo '<span class="list-bogo">BOGO</span>' ;
								
							} ?>
                        </span>
                      </div>
						
                        
                        <?php  $block->getProductDetailsHtml($_product) ?>

                          <!-- <div class="product-item-inner">
                         <div class="product actions product-item-actions"<?= strpos($pos, $viewMode . '-actions') ? $position : '' ?>>
                                <div class="actions-primary"<?= strpos($pos, $viewMode . '-primary') ? $position : '' ?>>
                                    <?php if ($_product->isSaleable()): ?>
                                        <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                        <form data-role="tocart-form" data-product-sku="<?= $block->escapeHtml($_product->getSku()) ?>" action="<?= /* @NoEscape */ $postParams['action'] ?>" method="post">
                                            <input type="hidden" name="product" value="<?= /* @escapeNotVerified */ $postParams['data']['product'] ?>">
                                            <input type="hidden" name="<?= /* @escapeNotVerified */ Action::PARAM_NAME_URL_ENCODED ?>" value="<?= /* @escapeNotVerified */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                            <?= $block->getBlockHtml('formkey') ?>
                                            <button type="submit"
                                                    title="<?= $block->escapeHtml(__('Add to Cart')) ?>"
                                                    class="action tocart primary">
                                                <span><?= /* @escapeNotVerified */ __('Add to Cart') ?></span>
                                            </button>
                                        </form>
                                    <?php else: ?>
                                        <?php if ($_product->isAvailable()): ?>
                                            <div class="stock available"><span><?= /* @escapeNotVerified */ __('In stock') ?></span></div>
                                        <?php else: ?>
                                            <div class="stock unavailable"><span><?= /* @escapeNotVerified */ __('Out of stock') ?></span></div>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                </div>
                                <div data-role="add-to-links" class="actions-secondary"<?= strpos($pos, $viewMode . '-secondary') ? $position : '' ?>>
                                    <?php if ($addToBlock = $block->getChildBlock('addto')): ?>
                                        <?= $addToBlock->setProduct($_product)->getChildHtml() ?>
                                    <?php endif; ?>
                                </div>
                            </div>
                            <?php if ($showDescription):?>
                                <div class="product description product-item-description">
                                    <?= /* @escapeNotVerified */ $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                    <a href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>" title="<?= /* @escapeNotVerified */ $_productNameStripped ?>"
                                       class="action more"><?= /* @escapeNotVerified */ __('Learn More') ?></a>
                                </div>
                            <?php endif; ?>
                        </div>-->
                    </div>
                
				</div>
				</div>
                <!--<?= ($iterator == count($_productCollection)+1) ? '</li>' : '' ?> -->
            <?php endforeach; ?>
        </div>
		</div>
    </div>
    <?php //$block->getToolbarHtml() ?>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {
                    "product_sku": "<?= /* @NoEscape */ $_product->getSku() ?>"
                }
            }
        }
        </script>
    <?php endif; ?>
<?php endif; ?>
<?php }?>



 <script type="text/javascript">
function popupSubcategory(obj)
{
jQuery(document).ready(function($){
  //alert(obj);
  var  str = window.location.href ;
  var n = str.includes("?");
  var url = new URL(str);
  var c = url.searchParams.get("id");
  if((n == true)){
	var res = str.replace(c,obj);
    var newurl = res ;
  }else{
	 var newurl =  window.location.href+'?id='+obj ; 
  }
  //var vediourl = $("#idvedio-"+obj).val();
  $("#loderpop").addClass("showpopup");
  //jQuery("#loderpop").addClass("showpopup");
  //alert(vediourl);
  $.ajax({
        url: "<?php echo $this->getBaseUrl()?>shopall/index/shopcategries/",
        type: "GET",
        data:  {"id":obj},
        success: function(response){
			//alert(response);
			
		$('#shopallproduct').html(response);	
		//$("#popup-modal1").modal("openModal");
		
		 window.history.pushState({ path: newurl }, '', newurl);
		  $("#loderpop").removeClass("showpopup");
        }
	  });
 
});
}
</script>

<script type="text/javascript">
require([ 'jquery'], function($){
$(document).ready(function($){
  var  str = window.location.href ;
  var n = str.includes("?");
   var url = new URL(str);
  var c = url.searchParams.get("id");
	if((c == true)){
    $("#loderpop").addClass("showpopup");
	 $.ajax({
        url: "<?php echo $this->getBaseUrl()?>shopall/index/shopcategries/",
        type: "GET",
        data:  {"id":c},
        success: function(response){
			//alert(response);
			
		$('#shopallproduct').html(response);	
		//$("#popup-modal1").modal("openModal");
		$("#loderpop").removeClass("showpopup");
		 //window.history.pushState({ path: newurl }, '', newurl);
        }
	  });
	 
	 }  
	
	
	});
});	
</script>