<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Form\Login $block */
?>

<div class="col-md-6 col-12 left-col" data-aos="fade-up" data-aos-offset="150"  data-aos-easing="ease-in-sine">
    <!--<div class="block-title">
        <strong id="block-customer-login-heading" role="heading" aria-level="2"><?= $block->escapeHtml(__('Registered Customers')) ?></strong>
    </div>-->
	
    <div class="signin-bx account-bx" aria-labelledby="block-customer-login-heading">
        <div class="form-group">
                          <h3>Welcome Back</h3>
                          <p class="text">Registered Jerome Alexander Customer</p>
                        </div>
						
		<form class="form form-login"
              action="<?= $block->escapeUrl($block->getPostActionUrl()) ?>"
              method="post"
              id="login-form"
              data-mage-init='{"validation":{}}'>
            <?= $block->getBlockHtml('formkey') ?>
           

		   <!--<fieldset class="fieldset login" data-hasrequired="<?= $block->escapeHtml(__('* Required Fields')) ?>">
              </fieldset>-->               
			   <!--<div class="field note"><?= $block->escapeHtml(__('If you have an account, sign in with your email address.')) ?></div>-->
                <div class="field email form-group required">
                    <label class="label" for="email"><?= $block->escapeHtml(__('Email')) ?> <span>*</span></label>
                    <input name="login[username]" value="<?= $block->escapeHtmlAttr($block->getUsername()) ?>" <?php if ($block->isAutocompleteDisabled()): ?> autocomplete="off"<?php endif; ?> id="email" type="email" class="input-text form-control" title="<?= $block->escapeHtmlAttr(__('Email')) ?>" data-mage-init='{"mage/trim-input":{}}' data-validate="{required:true, 'validate-email':true}">
                   
                </div>
                <div class="field form-group password required">
                    <label for="pass" class="label"><?= $block->escapeHtml(__('Password')) ?> <span>*</span>
					 <a href="<?= $block->escapeUrl($block->getForgotPasswordUrl()) ?>" class="forgot-link"><?= $block->escapeHtml(__('Forgot Your Password?')) ?></a>
                       
					</label>
                    <input  id="password" name="login[password]" type="password" <?php if ($block->isAutocompleteDisabled()): ?> autocomplete="off"<?php endif; ?> class="input-text form-control" id="pass" title="<?= $block->escapeHtmlAttr(__('Password')) ?>" data-validate="{required:true}">
                    <a href="javascript:void(0);" id ="check-eye" class="view-password-link">
                    <i class="fa fa-eye-slash"></i>
                    </a>
                </div>
              
				
				<div class="form-group remember-group">
                          <div class="remember-col custom-control custom-radio">
                             <?php echo $block->getChildHtml('form_additional_info'); ?>
					     <input type="checkbox" class="custom-control-input" name="radio" id="radioRemember">
						<label class="custom-control-label" for="radioRemember">Remember Me</label>
                          
						   </div>
                        </div>
				
				 <div class="form-group btn-group">
                  <button type="submit" class="action btn btn-primary btn-4" name="send" id="send2"><?= $block->escapeHtml(__('Sign In')) ?></button>	
					</div>
						
						
               <!-- <div class="actions-toolbar">
                    <div class="primary"><button type="submit" class="action login primary" name="send" id="send2"><span><?= $block->escapeHtml(__('Sign In')) ?></span></button></div>
                    <div class="secondary"><a class="action remind" href="<?= $block->escapeUrl($block->getForgotPasswordUrl()) ?>"><span><?= $block->escapeHtml(__('Forgot Your Password?')) ?></span></a></div>
                </div>-->
           
        </form>
    </div>
	
	
	
</div>



<script type="text/javascript">
require([ 'jquery'], function($){

$(document).ready(function(){
	
$('#check-eye').click(function(){
       //alert('++')    
  if('password' == $('#password').attr('type')){
         $('#password').prop('type', 'text');
    }else{
         $('#password').prop('type', 'password');
    }
	
 });	
 
 


 });	


});
</script>
