<div class="footer-top">
<div class="container">
              <div class="row">
                <div class="col-md-6 col-12 left-col">
                  <p>No Risk. Jerome Alexander <span>100% Satisfaction Guarantee</span>.</p>
                </div>
                <div class="col-md-6 col-12 right-col">
                  <p>Free Shipping on Orders over $50</p>
                </div>
              </div>
            </div>
     </div>    
<div class="footer-bottom">
<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer_bottom')->toHtml(); ?>	
 </div>
	 
	 
<script type="text/javascript">
    require(['aos'], function (AOS) {
		AOS.init({
                  duration: 1200,
         });	
		
	
	 });
		

</script>		 