<div class="container">
              <div class="row">
                <div class="col-md-6 col-12 left-col">
                  <p>No Risk. Jerome Alexander <span>100% Satisfaction Guarantee</span>.</p>
                </div>
                <div class="col-md-6 col-12 right-col">
                  <p>Free Shipping on Orders over $50</p>
                </div>
              </div>
            </div>
     

