<?php
/**
 * Blackbird ContentManager Module
 *
 * NOTICE OF LICENSE
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to contact@bird.eu so we can send you a copy immediately.
 *
 * @category        Blackbird
 * @package         Blackbird_ContentManager
 * @copyright       Copyright (c) 2018 Blackbird (https://black.bird.eu)
 * @author          Blackbird Team
 * @license         https://www.advancedcontentmanager.com/license/
 */
?>
<?php
/**
 * @see \Blackbird\ContentManager\Block\ContentList
 * @var \Blackbird\ContentManager\Block\ContentList $block
 */
?>
<?php
$collection = $block->getCollection();
/** @var \Blackbird\ContentManager\Model\ContentList $contentList */
$contentList = $block->getContentList();
$link = $block->getLink();
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$base_url = $storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_WEB);

//echo "<pre>";print_r($block->getActiveFilters()) ;

?>


<div class="breadcrumbs">
              <ul class="items">
                  <li class="item home"><a href="index.html">Home</a></li>
                  <li class="item">Ask Jerome</li>
              </ul>
          </div>

	<div class="ask-container">

      <div class="sidebar-ask">
		<div class="filter-tutorials-m">
			<span>Filter Tutorials</span>
			<i class="fa fa-minus" aria-hidden="true"></i>
		</div>
         <div class="sidebar-filter row-col" data-aos="fade-up" data-aos-offset="150"  data-aos-easing="ease-in-sine">
             <h5>Choose all that apply:</h5>
               <h6>I'm interested in:</h6>
                <ul class="filter-ul">
				<?php 
				if(!empty($_GET['asfjerome_interested'])){
					$asfjerome_interested = $_GET['asfjerome_interested'];
				}else{
				$asfjerome_interested = 'dd';	
				} 
				?>
				
				<?php 
				if(!empty($_GET['asfjerome_like_to'])){
					$asfjerome_like_to = $_GET['asfjerome_like_to'];
				}else{
				$asfjerome_like_to = 'dd';	
				} 
				?>
                  <li class="custom-control custom-radio">
                   <input type="radio" name="asfjerome_interested" class="custom-control-input" value="face" id="customRadio1"  <?php if($asfjerome_interested == 'face'){echo 'checked';} ?>>
                   <label class="custom-control-label" for="customRadio1">Face</label>
                   </li>
                   <li class="custom-control custom-radio">
                    <input type="radio" name="asfjerome_interested" class="custom-control-input"  value="cheeks" id="customRadio2" <?php if($asfjerome_interested == 'cheeks'){echo 'checked';} ?>>
                    <label class="custom-control-label" for="customRadio2">Cheeks</label>
                   </li>
                   <li class="custom-control custom-radio">
                    <input type="radio" name="asfjerome_interested" class="custom-control-input" value="eyes" id="customRadio3" <?php if($asfjerome_interested == 'eyes'){echo 'checked';} ?>>
                    <label class="custom-control-label" for="customRadio3">Eyes</label>
                    </li>
                   <li class="custom-control custom-radio">
                     <input type="radio" name="asfjerome_interested"class="custom-control-input" value="lips" id="customRadio4"  <?php if($asfjerome_interested =='lips'){echo 'checked';} ?>>
                     <label class="custom-control-label" for="customRadio4">Lips</label>
                    </li>
                   <li class="custom-control custom-radio">
                     <input type="radio" name="asfjerome_interested" class="custom-control-input" value="makeup-tips-education" id="customRadio5" <?php if($asfjerome_interested == 'makeup-tips-education'){echo 'checked';} ?>>
                     <label class="custom-control-label" for="customRadio5">Makeup Tips & Education</label>
                   </li>
                   <li class="custom-control custom-radio">
                     <input type="radio" name="asfjerome_interested" class="custom-control-input" value="glamour" id="customRadio6" <?php if($asfjerome_interested == 'glamour'){echo 'checked';} ?>>
                     <label class="custom-control-label" for="customRadio6">Glamour</label>
                   </li>
                  </ul>
						
                 <h6>I would like to:</h6>
                 <ul class="filter-ul">
				   <li class="custom-control custom-radio">
                    <input type="radio" name="asfjerome_like_to" class="custom-control-input" value="videos" id="customRadio7" <?php if($asfjerome_like_to == 'videos'){echo 'checked';} ?>>
                    <label class="custom-control-label" for="customRadio7">Watch Videos</label>
                   </li>
                   <li class="custom-control custom-radio">
                     <input type="radio" name="asfjerome_like_to" class="custom-control-input" value="read" id="customRadio8" <?php if($asfjerome_like_to == 'read'){ echo 'checked';} ?>>
                    <label class="custom-control-label" for="customRadio8">Read Tutorials</label>
                   </li>
                 </ul>
              <div class="side-btn">
               <button type="button" class="btn btn-primary btn1">Clear</button>
				<button type="button" class="btn btn-primary btn2">Done</button>
              </div>
						
						
             </div>
             </div>
					
					
			<div class="ask-jerome-banner banner-notfront row-col">
					<figure>
						<?= $block->getTextBefore() ?>
					</figure>
					<div class="caption-inner">
					<?php if (!empty($block->getTitle())) : ?>
					 <h1 class="title-main"><?= $block->getTitle() ?></h1>
					<?php endif; ?>
							
						<?= $block->getTextAfter() ?>
					</div>
				</div>	
                    
					
					
			<div class="column-ask">
                      <!--ask-jerome-inner-->
                      <div class="ask-jerome-inner row-col" data-aos="fade-up" data-aos-offset="150"  data-aos-easing="ease-in-sine">
						
						
						
						
						
						
				<!--popular-tutorials-->
				<div class="popular-tutorials row-col">
				<h2 class="title-main title2">Popular Tutorials</h2>
				<div class="popular-list row-col">
				<div class="row">
				<?php if ($collection->count()) : ?>
            
		         <?php foreach ($collection as $content) : ?>
				 <?php //$interested= (explode(",",$content->getData('asfjerome_like_to'))); 
				 $interested=  $content->getData('asfjerome_like_to') ; 
				 //echo($interested);
				 ?>
				 <?php if($interested = 'videos'){ ?>
				
				<div class="col-md-4 col-12">
					<div class="popular-item">
					<div class="video-col">
					
					<img src="<?= $content->getImage('thimble_images')?>" class="img-fluid" />
			       <div class="play-tutorial">
					<a href="javascript:void(0);" class="icon click-me bt-action"  data="More Info"  data-type="<?php echo $content->getId();?>" id="video_titorial_<?php echo $content->getId(); ?>" >
					<i class="fa"><img src="<?php echo $base_url ;?>pub/media/themeimage/arrow-right-white.png"></i>
					<span>Play Tutorial</span>
					</a>
					</div>
					</div>
					<div class="info-col">
				    <p><?= $content->getData('asfjerome_title'); ?></p>
					<!--<a href="<?= $content->getLinkUrl(); ?>" class="read-more-link">Read More</a>-->
					</div>
					</div>
					</div>
					

					
				 <?php } ?>	
	   <?php endforeach; ?>
	   
	    <?php foreach ($collection as $content) : ?>
				 <?php $interested1= (explode(",",$content->getData('asfjerome_like_to'))); 
				 print_r($interested1);
				 $interested= $content->getData('asfjerome_like_to'); 
			echo($interested);
				 
				 ?>
			<?php if($interested = 'read'){ ?>
				
				<div class="col-md-4 col-12">
					<div class="popular-item">
					<div class="video-col">
					
					<img src="<?= $content->getImage('thimble_images')?>" class="img-fluid" />
			       <div class="play-tutorial">
					<a href="javascript:void(0);" data="More Info"  class="icon bt-action" data-type="<?php echo $content->getId();?>" id="video_titorial_<?php echo $content->getId();?>" >
					<i class="fa"><img src="<?php echo $base_url ;?>pub/media/themeimage/arrow-right-white.png"></i>
					<span>Play Tutorial</span>
					</a>
					</div>
					</div>
					<div class="info-col">
				    <p><?= $content->getData('asfjerome_title'); ?></p>
					<a href="<?= $content->getLinkUrl(); ?>" class="read-more-link">Read More</a>
					</div>
					</div>
					</div>
					
					<div class="bt-action-file" style="display: none;"> 
				 <iframe id="cartoonVideo-<?php echo $content->getId();?>" width="560" height="315" src="//www.youtube.com/embed/YE7VzlLtp-4?rel=0&modestbranding=1&autohide=1&mute=1&showinfo=0&controls=0&autoplay=1" frameborder="0"  allow="autoplay ,fullscreen" style="border: solid 4px #37474F"></iframe>
 	                  </div>
  
					
				 <?php } ?>	
	   <?php endforeach; ?>
	   <?php else: ?>
            <div class="message info empty">
                <span><?= __('We can\'t find contents matching the selection.') ?></span>
            </div>
        <?php endif; ?>				
									
									
				<div class="col-12 pagination-col">
										
				<?php if ($block->hasPagerBottom()) : ?>
                <div class="toolbar-bottom">
                    <div class="toolbar bottom">
                        <?= $block->getPagerHtml(); ?>
                    </div>
                </div>
            <?php endif; ?>
			 </div>	
		        
				</div>
				</div>
				</div>
		<!--/popular-tutorials-->
				              		
                          

                         

                      </div>
                    <!--/ask-jerome-inner-->

                   
                   
                    </div>
        
          
		</div>






 


            
		
			
    
            <!--<a  href="<?php //echo $content->getLinkUrl(); ?>">
			</a>-->
        	<?php  //echo $content->getData('asfjerome_video'); ?>
  
       
					
			
          


<a href="javascript:;"  class="bt-action" data="More Info"  >More Info</a>


<script>
    require(
        [
            'jquery',
            'Magento_Ui/js/modal/modal'
        ],
        function(
            $,
            modal
        ) {
            var options = {
                type: 'popup',
                responsive: true,
                innerScroll: true,
                title: 'popup modal title',
                buttons: [{
                    text: $.mage.__('Continue'),
                    class: '',
                    click: function () {
                        this.closeModal();
                    }
                }]
            };
 
        
		//var popup = modal(options, $('#popup-modal' ));
            $("click-me").on('click',function(){ 
			
			var link = $(this).attr("data-type");
			var popup = modal(options, $('#popup-modal-'+link ));
			$("#popup-modal-"+link).modal("openModal");
			var url = $("#cartoonVideo-"+link).attr('src');
            $("#cartoonVideo-"+link).attr('src', '');
			$("#cartoonVideo-"+link).attr('src', url);
    
	
 

 });


        }
    );
	
	
	
	require(
        [
            'jquery',
            'Magento_Ui/js/modal/modal'
        ],
        function(
            $,
            modal
        ) {

            var options = {
                type: 'popup',
                responsive: true,
                innerScroll: false,
                title: 'My Title',
                buttons: []
            };

            $(".bt-action").click(function() {

                $(".bt-action-file").modal(options).modal('openModal');

            });

        }
    );
</script>	 

 



  
			
			

<script>
require([
	'jquery',
	], function () {
	jQuery(document).ready(function($) {
	 jQuery('.breadcrumbs').detach().insertBefore('.page-main');
   //jQuery(".toolbar-bottom").detach().insertAfter(".contents-items.widget-content-grid");		
   jQuery(".btn2").click(function(){
	 
     var interested = $("input[name='asfjerome_interested']:checked").val();
     var like_to = $("input[name='asfjerome_like_to']:checked").val();
     if (typeof interested === "undefined") {
       var value1 = '';
	 }else{
		var value1 = 'asfjerome_interested='+interested ;
	 }
	 if (typeof like_to === "undefined") {
       var value2 = '';
	 }else{
		var value2 = 'asfjerome_like_to='+like_to ;
	 }
	 var val = value2+'&'+value1 ;
	//alert(val);
	var baseurl = '<?php echo $base_url.'ask-jerome'?>';
	
	window.location.href = baseurl+'?'+val;
	});
   
    jQuery(".btn1").click(function(){
	var baseurl = '<?php echo $base_url.'ask-jerome'?>';	
	window.location.href = baseurl;	
	});

	//filter tutorials jQuery
	jQuery(".filter-tutorials-m").on("click", function(){
		jQuery(this).next(".sidebar-filter").slideToggle();	
	})

   });
});
</script>