<?php
/**
 * Blackbird ContentManager Module
 *
 * NOTICE OF LICENSE
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to contact@bird.eu so we can send you a copy immediately.
 *
 * @category        Blackbird
 * @package         Blackbird_ContentManager
 * @copyright       Copyright (c) 2018 Blackbird (https://black.bird.eu)
 * @author          Blackbird Team
 * @license         https://www.advancedcontentmanager.com/license/
 */
?>
<?php
/**
 * @see \Blackbird\ContentManager\Block\ContentList
 * @var \Blackbird\ContentManager\Block\ContentList $block
 */
?>
<?php
$collection = $block->getCollection();
/** @var \Blackbird\ContentManager\Model\ContentList $contentList */
$contentList = $block->getContentList();
$link = $block->getLink();

echo "<pre>";print_r($block->getActiveFilters()) ;
?>
<div class="block widget contents-grid grid ct-view ct-listing-<?= $contentList->getUrlKey() ?>"
     id="ct-listing-<?= $contentList->getId() ?>">
    <?php if (!empty($block->getTitle())) : ?>
        <div class="block-title">
            <strong><?= $block->getTitle() ?></strong>
        </div>
    <?php endif; ?>
    <div class="block-content">

        <div class="text-before"><?= $block->getTextBefore() ?></div>
<?= $block->getPagerHtml(); ?>
        <?php if ($collection->count()) : ?>

            <?php if ($block->hasPagerTop()) : ?>
                <div class="toolbar-bottom">
                    <div class="toolbar top">
                        <?= $block->getPagerHtml(); ?>
                    </div>
                </div>
            <?php endif; ?>

            <div class="contents-items widget-content-grid">
                <?php foreach ($collection as $content) : ?>
				 <?php //echo $content->getData('created_at');?>
				 
			<div class="content-item">
		    
			<a  href="<?= $content->getLinkUrl(); ?>">
			<img src="<?= $content->getImage('thimble_images')?>" />
			</a>
			<a  href="<?= $content->getLinkUrl(); ?>">
			 <?= $content->getData('asfjerome_title'); ?>
			</a>
			<a  href="<?= $content->getLinkUrl(); ?>"><?= __($link['label']); ?></a>
			<?= $content->getData('asfjerome_video'); ?>
			<?php echo date('jS \of F Y',strtotime($content->getData('created_at'))); ?>
			
			<?php print_r($content->getData('asfjerome_interested')); ?>
			<?php print_r($content->getData('asfjerome_like_to')); ?>
			
			 
			 </div>	
                    
                <?php endforeach; ?>
            </div>

            <div style="clear: both"></div>

            <?php if ($block->hasPagerBottom()) : ?>
                <div class="toolbar-bottom">
                    <div class="toolbar bottom">
                        <?= $block->getPagerHtml(); ?>
                    </div>
                </div>
            <?php endif; ?>

        <?php else: ?>
            <div class="message info empty">
                <span><?= __('We can\'t find contents matching the selection.') ?></span>
            </div>
        <?php endif; ?>

        <div class="text-after"><?= $block->getTextAfter() ?></div>
    </div>
</div>
