<?php
/**
 * Blackbird ContentManager Module
 *
 * NOTICE OF LICENSE
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to contact@bird.eu so we can send you a copy immediately.
 *
 * @category        Blackbird
 * @package         Blackbird_ContentManager
 * @copyright       Copyright (c) 2018 Blackbird (https://black.bird.eu)
 * @author          Blackbird Team
 * @license         https://www.advancedcontentmanager.com/license/
 */
?>
<?php
/**
 * @see \Blackbird\ContentManager\Block\View
 */
?>
<?php
/*
 * 
 * 
 * AVAILABLE METHODS
 * 
 * Get all raw values as an array
 * $content->getData();
 * 
 * Get a specific value by his field identifier
 * $content->getData('field_identifier');
 * $content->getFieldIdentifier();
 * $content->getAttributeText('field_identifier');
 * 
 * Get content type model
 * $content->getContentType();
 * 
 * Get image URL for an image field type.
 * $content->getImage($attributeName, $width, $height, $keepRatio, $cropped = false);
 * 
 * Get file absolute URL, for a file field typ
 * $content->getFile($field_identifier);
 * 
 * Get content url
 * $content->getLinkUrl();
 * 
 * Render a field in HTML
 * $content->render($element, $params);
 * 
 * See the complete documentation and more examples at:
 * http://www.advancedcontentmanager.com/documentation/
 * 
 */
?>
<?php
/** @var \Blackbird\ContentManager\Model\Content $content */
$content = $block->getContent();
/** @var \Blackbird\ContentManager\Model\ContentType $contentType */
$contentType = $content->getContentType();
//$repeaterValues = $content->getContentCollection('about_us_gasser_images', '*');
$identifier = $contentType->getIdentifier();

 $om = \Magento\Framework\App\ObjectManager::getInstance();
    $storeManager = $om->get('\Magento\Store\Model\StoreManagerInterface');
   $media_url =$storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
?>


<div class="ask-detail-banner row-col" data-aos="fade-up" data-aos-offset="150"  data-aos-easing="ease-in-sine">
			<div class="container">
			<?php if(!empty($content->getData('asfjerome_banner'))){?>
				<figure>
					<img src="<?php echo $media_url ; ?>contentmanager/content/<?php echo $content->getData('asfjerome_banner'); ?>" alt="<?php echo $content->getData('asfjerome_title'); ?>" class="img-fluid">
				</figure>
			<?php }?>	
				<div class="ask-caption">
					<div class="tag-title">
						<?php $interested= (explode(",",$content->getData('asfjerome_interested'))); ?>
						<?php foreach($interested as $item){?>
						<span> <?php echo $item ;?></span>
					   <?php }?>
					</div>
					<div class="title">
						<h1><?php echo $content->getData('asfjerome_title'); ?></h1>
						<span><?php echo date('jS \of F Y',strtotime($content->getData('created_at'))); ?></span>
					</div>
				</div>
			</div>
		</div>

  <div class="breadcrumbs">
              <ul class="items">
				  <li class="item home"><a href="<?php echo $this->getUrl('');?>">Home</a></li>
				  <li class="item"><a href="<?php echo $this->getUrl('ask-jerome/');?>">Ask Jerome</a></li>
                  <li class="item"><?php echo $content->getData('asfjerome_title'); ?></li>
              </ul>
          </div>
		  
		  
		  
	 <div class="ask-jerome-detail-container" data-aos="fade-up" data-aos-offset="150"  data-aos-easing="ease-in-sine">
						

						<div class="jerome-description row-col">
							<div class="content">
					  <?= $content->getData('ask_description'); ?>
		  
		  
		                  </div>
		  
		              	<div class="social-col ask-social-col">
									<ul class="social-links">
									<li class="beauty-li">SHARE BEAUTY</li>
									<li class="facebook-link">
										<a href="javascript:void(0);">
											<img src="<?php echo  $media_url ; ?>themeimage/facebook-icon.png" alt="">
										</a>
									</li>
									<li class="twitter-link">
										<a href="javascript:void(0);">
											<img src="<?php echo  $media_url ; ?>themeimage/twitter-icon.png" alt="">
										</a>
									</li>
									<li class="pinterest-link">
										<a href="javascript:void(0);">
											<img src="<?php echo  $media_url ; ?>themeimage/pinterest-icon.png" alt="">
										</a>
									</li>
									<li class="email-link">
										<a href="javascript:void(0);">
											<img src="<?php echo  $media_url ; ?>themeimage/envelope-icon.png" alt="">
										</a>
									</li>
									<li class="link-link">
										<a href="javascript:void(0);">
											<img src="<?php echo  $media_url ; ?>themeimage/link-icon.png" alt="">	
										</a>
									</li>
									</ul>
								</div>
		            
		             </div>
	</div>	  
		  





		
			









<script>
    require([
        'jquery'
    ], function ($) {
        $(document).ready(function(){
            // move hero banner to top of the page
            $('.ask-detail-banner').detach().insertAfter('.page-wrapper > .nav-sections');

            // move the bottom outside main wrapper as well as it needs to have full width
    $('.breadcrumb').detach().insertAfter('.page-wrapper > .nav-sections > .sask-detail-banner');
        })
    })
</script>

