<?php 
	$enable = $block->getConfig('enabled');
	if($enable < 1) return ; 
	$items = $block->getConfig('items');
	$itemsDefault = $block->getConfig('itemsDefault');
	$itemsDesktop = $block->getConfig('itemsDesktop'); 
	$itemsDesktopSmall = $block->getConfig('itemsDesktopSmall');
	$itemsTablet = $block->getConfig('itemsTablet');
	$itemsMobile = $block->getConfig('itemsMobile');
	$title = $block->getConfig('title');
	$speed = $block->getConfig('speed');
	$qty = $block->getConfig('qty');
	$showCart = $block->getConfig('addtocart');
	$showWishlist = $block->getConfig('wishlist');
	$showCompare = $block->getConfig('compare');
	$show_navigation = $block->getConfig('navigation');
	$show_pagination = $block->getConfig('pagination'); 
	$auto = $block->getConfig('auto');
	$rows = $block->getConfig('row');
?>


<div class="magic-makeup-row" data-aos="fade-up" data-aos-offset="150"  data-aos-easing="ease-in-sine">
<div class="container">
 <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('magic-makeup-row')->toHtml(); ?>
<div class="magic-carousel">
   <div class="magic-descript">
    <h3 class="title-main"><?php echo $title; ?></h3>
    <div class="magic-para">
	<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('magic-makeup-content')->toHtml(); ?>
    </div>
	</div>
<div class="owl-carousel owl-theme">
  <?php 
	$newItems = $block ->getNewProduct()->getItems(); 
	$imageBlock =  $block->getLayout()->createBlock('Magento\Catalog\Block\Product\Image');
	$image = 'new_products_content_widget_grid';
	$type = 'widget-new-grid';
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::DEFAULT_VIEW;
	$i=0;
	foreach($newItems as $_item) { 
		$productImage = $block->getImage($_item, $image);
		$productImagess= $this->getMediaUrl().'catalog/product'.$_item->getImage();
		?>
					 <div class="item">
                          <div class="magic-item">
                          <img src="<?php echo $productImagess ;?>" class="img-fluid" />
                            <div class="seller-info">
                             <?php if ($templateType): ?>
							<?php echo $block->getReviewsSummaryHtml($_item, $templateType,true); ?>
							<?php endif; ?>
                                  <div class="seller-name-col">
                                    <a href="<?php echo $block->getProductUrl($_item) ?>" class="title-name"> <?php echo $block->escapeHtml($_item->getName()) ?></a>
                                    <p><?php echo $_item->getShortDescription(); ?></p>
                                  </div>
                                  <div class="shopnow-col">
                                      <a href="<?php echo $block->getProductUrl($_item) ?>" class="shopnow-btn">Shop Now</a>
                                  </div>
                              </div>
                           </div> 
                      </div> 
	<?php } ?>		  
					  
                     
					  
					  
                    
                     

                  </div>
                </div>
              </div>
            </div>




<script type="text/javascript">
require([
  "jquery",
  "owlcarousel/minjs"
 ], function($,owlCarousel){
	
 //magic makeup carousel
        $('.magic-carousel .owl-carousel').owlCarousel({
            loop: true,
            margin: 15,
            nav: true,
            dots: false,
            smartSpeed: 500,
            responsive: {
                0: {
                    items: 1
                },
                500: {
                    items: 2
                },
                768: {
                    items: 2
                },
                992: {
                    items: 3
                }
            }
        });
   
});
</script>   