<?php echo $block->getLayout()->createBlock('Saffron\Bannerslider\Block\Bannerslider')->setTemplate('bannerslider.phtml')->toHtml();?> 
<?php echo $block->getLayout()->createBlock('Saffron\Bestsellerproduct\Block\Bestsellerproduct')->setTemplate('bestsellerproduct.phtml')->toHtml();?> 
<?php //echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('bestsellerproduct')->toHtml(); ?>
<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('real-women-row')->toHtml(); ?>
<?php echo $block->getLayout()->createBlock('Saffron\Newproductslider\Block\Newproductslider')->setTemplate('newproductslider.phtml')->toHtml();?> 
<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('clock1-home')->toHtml(); ?>
<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('clock2-home')->toHtml(); ?>	
<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('ask-jerome-home')->toHtml(); ?>	
<?php echo $block->getLayout()->createBlock('Saffron\Bannerslider\Block\Homecategries')->setTemplate('homecategries.phtml')->toHtml();?> 
<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('palettes-gift-row')->toHtml(); ?>	
<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('get-social')->toHtml(); ?>	

<style>
main#maincontent {
    display: none;
}
</style>