<?php echo $block->getLayout()->createBlock('Saffron\Bannerslider\Block\Bannerslider')->setTemplate('bannerslider.phtml')->toHtml();?> 
<?php echo $block->getLayout()->createBlock('Saffron\Bestsellerproduct\Block\Bestsellerproduct')->setTemplate('bestsellerproduct.phtml')->toHtml();?> 
<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('real-women-row')->toHtml(); ?>
<?php echo $block->getLayout()->createBlock('Saffron\Newproductslider\Block\Newproductslider')->setTemplate('newproductslider.phtml')->toHtml();?> 
		