
<?php  $myVar = $block->getData('product_sku');?>
<?php $skulist = explode(",",$myVar); ?>

<div class="foundation-shades row-section" id="foundation-shades">
<div class="container">
 <div class="shades-boxes">   
<h2>Foundation Shades</h2>
    <ul class="tabs">
<?php $i= 1;  foreach ($skulist as  $item) {
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();  
$productRepository = $objectManager->get('\Magento\Catalog\Model\ProductRepository');
$product = $productRepository->get($item);
//echo $product['foundation_shades']; 

$resource = $objectManager->get('Magento\Framework\App\ResourceConnection');
$connection = $resource->getConnection();
$tableName = $resource->getTableName('eav_attribute_option_swatch');
$sql = "Select * FROM " . $tableName . " WHERE  option_id= ".$product['foundation_shades'];
$result = $connection->fetchAll($sql);
$attr = $product->getResource()->getAttribute('foundation_shades');

?>

 
<?php  if ($attr->usesSource()) {?>
    <li style="background: <?php echo $result[0]['value'] ;?> no-repeat center;
    background-size: initial;"    class="swatch-option tab-link <?php if($i=='1'){echo 'current';}?>" data-tab="tab-<?php echo $i ;?>"  > 
    <a href="javascript:void(0); <?php //echo $product->getProductUrl() ;?>">
    </a>
    <span> <?php echo  $optionText = $attr->getSource()->getOptionText($product['foundation_shades']) ?>
    </span>
    </li>
<?php }?>




 <?php  $i++ ;}  ?>
</ul>


<?php  $i= 1;foreach ($skulist as  $item) {
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();  
$productRepository = $objectManager->get('\Magento\Catalog\Model\ProductRepository');
$product = $productRepository->get($item);

//echo $item ;
?>
<?php $objectManager = \Magento\Framework\App\ObjectManager::getInstance();

  $listBlock = $objectManager->get('\Magento\Catalog\Block\Product\ListProduct');

  $addToCartUrl =  $listBlock->getAddToCartUrl($product); ?>


<div class="newaddtocartcontaint tab-content <?php if($i=='1'){echo 'current';}?>"  id="tab-<?php echo $i ;?>" >

 <form data-role="tocart-form" action="<?php echo $addToCartUrl; ?>" method="post"> 
   <div class="quanty-col">

        <input id="IncDec-<?php echo $i ?>"  name="qty" type="number" value="1"  data-validate="{"required-number":true,"validate-item-quantity":{"minAllowed":1,"maxAllowed":10000}}"   /> 

        <button class="btnAdd" type="button">+</button> <button class="btnMin" type="button">-</button></div>
    <?php echo $block->getBlockHtml('formkey')?>

     <button type="submit" title="Add to Cart" class="action tocart  buynow-link">

       <span>Buy Now</span>
     </button>
 </form>



 
</div>
<script>
require([
    'jquery',
    ], function () {
    jQuery(document).ready(function($) {
       
  //increase-decrease input quantity javascript
        var i = 0;
        var x = document.querySelector('#IncDec-<?php echo $i ?>');
        function addValue(){
            $('.btnAdd').click(function(){
                if( x.value >= i ){
                    i++;
                    var y = x.value = i;
                }
            })
        }
        addValue();
        
        function decValue(){
            $('.btnMin').click(function(){
                if( x.value >= 1 ){
                    i--;
                    var y = x.value = i;
                }
            })
        }
        decValue();
    });

   });

</script>


<?php $i++ ;}?>




</div>





<div class="shipped-txt">
<p>*This item cannot be shipped to P.O. Boxes, Alaska, Hawaii, Puerto Rico or Canada.</p>
</div>
</div>
</div>






<style type="text/css">
.shades-boxes li a {
    display: block;
    width: 100%;
    height: 100%;
}

.shades-boxes li {
    width: 140px;
    height: 140px;
}
        ul.tabs{
            margin: 0px;
            padding: 0px;
            list-style: none;
        }
        ul.tabs li{
            background: none;
            color: #222;
            display: inline-block;
            padding: 10px 15px;
            cursor: pointer;
        }

        ul.tabs li.current{
            border: 4px solid #530774;
            color: #222;
        }

        .tab-content{
            display: none;
            
            padding: 15px;
        }

        .tab-content.current{
            display: inherit;
        }

.cms-celebrating-50-years-of-beauty .page-wrapper .page-main .columns {
    max-width: 100%;
}
.cms-celebrating-50-years-of-beauty .page-wrapper .page-main .columns .column.main {
    padding-bottom: 0;
}
.cms-celebrating-50-years-of-beauty button.action.tocart.buynow-link:hover, .cms-celebrating-50-years-of-beauty button.action.tocart.buynow-link:focus {
    background: #c1739a;
}
.shades-boxes form {
    display: flex;
    padding: 0 0 20px;
    justify-content: center;
}
.quanty-col button {
    border-radius: 0;
    margin: 0;
}
.shades-boxes button.btnMin {
    bottom: 1px;
}
ul.tabs li {
    border: 4px solid transparent;
    outline: none;
    padding: 0;
}
.shades-boxes ul.tabs {float: left;width: 100%;text-align: center;}
.shades-boxes li {
    max-width: 100px;
    max-height: 100px;
}
.shades-boxes .tab-content.current {
    float: left;
    width: 100%;
    text-align: center;
}
.shades-boxes ul.tabs li {
    padding: 0;
    margin: 0 10px  70px;
    max-width: 120px;
    max-height: 120px;
}

.shades-boxes ul.tabs li span {
    display: flex;
    margin: 19px 0;
    justify-content: center;
}
</style>


<script>
require([
    'jquery',
    ], function () {
    jQuery(document).ready(function($) {

    
    jQuery('ul.tabs li').click(function(){
        //alert('+++')
        var tab_id = $(this).attr('data-tab');
          //alert(tab_id);
        jQuery('ul.tabs li').removeClass('current');
        jQuery('.tab-content').removeClass('current');

        jQuery(this).addClass('current');
        jQuery("#"+tab_id).addClass('current');
    })

})
});

</script>    