
<?php  $myVar = $block->getData('product_sku');?>
<?php $skulist = explode(",",$myVar); ?>

<div class="foundation-shades row-section">
<div class="container">
 <div class="shades-boxes">   
<h2>Foundation Shades</h2>

<?php  foreach ($skulist as  $item) {
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();  
$productRepository = $objectManager->get('\Magento\Catalog\Model\ProductRepository');
$product = $productRepository->get($item);
//echo $product['foundation_shades']; 

$resource = $objectManager->get('Magento\Framework\App\ResourceConnection');
$connection = $resource->getConnection();
$tableName = $resource->getTableName('eav_attribute_option_swatch');
$sql = "Select * FROM " . $tableName . " WHERE  option_id= ".$product['foundation_shades'];
$result = $connection->fetchAll($sql);
$attr = $product->getResource()->getAttribute('foundation_shades');

?>

 <?php $objectManager = \Magento\Framework\App\ObjectManager::getInstance();

  $listBlock = $objectManager->get('\Magento\Catalog\Block\Product\ListProduct');

  $addToCartUrl =  $listBlock->getAddToCartUrl($product); ?>




<?php  if ($attr->usesSource()) {?>
    <div style="background: <?php echo $result[0]['value'] ;?> no-repeat center;
    background-size: initial;"    class="swatch-option " > 
    <a href=" <?php echo $product->getProductUrl() ;?>">
    </a>
    <span> <?php echo  $optionText = $attr->getSource()->getOptionText($product['foundation_shades']) ?>
    </span>
    </div>
<?php }?>

<div class="qty-buy-col">

 <form data-role="tocart-form" action="<?php echo $addToCartUrl; ?>" method="post"> 
    <div class="quanty-col"><input id="IncDec"  name="qty" type="number" value="1"  data-validate="{"required-number":true,"validate-item-quantity":{"minAllowed":1,"maxAllowed":10000}}"/> <button class="btnAdd" type="button">+</button> <button class="btnMin" type="button">-</button></div>
    <?php echo $block->getBlockHtml('formkey')?>

     <button type="submit" title="Add to Cart" class="action tocart primary buynow-link">

       <span>Buy Now</span>
     </button>
 </form>

</div>


 <?php }  ?>






</div>





<div class="shipped-txt">
<p>*This item cannot be shipped to P.O. Boxes, Alaska, Hawaii, Puerto Rico or Canada.</p>
</div>
</div>
</div>



<div class="container">

    <ul class="tabs">
        <li class="tab-link current" data-tab="tab-1">Tab One</li>
        <li class="tab-link" data-tab="tab-2">Tab Two</li>
        <li class="tab-link" data-tab="tab-3">Tab Three</li>
        <li class="tab-link" data-tab="tab-4">Tab Four</li>
    </ul>

    <div id="tab-1" class="tab-content current">
        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
    </div>
    <div id="tab-2" class="tab-content">
         Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
    </div>
    <div id="tab-3" class="tab-content">
        Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
    </div>
    <div id="tab-4" class="tab-content">
        Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
    </div>

</div><!-- container -->



<style type="text/css">


        ul.tabs{
            margin: 0px;
            padding: 0px;
            list-style: none;
        }
        ul.tabs li{
            background: none;
            color: #222;
            display: inline-block;
            padding: 10px 15px;
            cursor: pointer;
        }

        ul.tabs li.current{
            background: #ededed;
            color: #222;
        }

        .tab-content{
            display: none;
            background: #ededed;
            padding: 15px;
        }

        .tab-content.current{
            display: inherit;
        }
</style>


<script>
require([
    'jquery',
    ], function () {
    jQuery(document).ready(function($) {

    
    jquery('ul.tabs li').click(function(){
        var tab_id = $(this).attr('data-tab');

        jQuery('ul.tabs li').removeClass('current');
        jQuery('.tab-content').removeClass('current');

        jQuery(this).addClass('current');
        jQuery("#"+tab_id).addClass('current');
    })

})
});

</script>    