
<!--<div class="block-group box-section">
	
	<div class="container">
		<div class="newpr-slider">
			<?php echo $block->getLayout()->createBlock('Saffron\Newproductslider\Block\Newproductslider')->setTemplate('newproductslider.phtml')->toHtml();?> 
		</div>	
		
	</div>


</div>-->


<div class="block-group">
<div class="testimo-slider">
			<?php echo $block->getLayout()->createBlock('Saffron\Testimonial\Block\Testimonial')->setTemplate('testimonial.phtml')->toHtml(); ?>
		</div>
</div> 
