
<?php  $myVar = $block->getData('product_sku');?>
<?php $skulist = explode(",",$myVar); ?>

<div class="foundation-shades row-section">
<div class="container">
 <div class="shades-boxes">   
<h2>Foundation Shades</h2>

<?php  foreach ($skulist as  $item) {
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();  
$productRepository = $objectManager->get('\Magento\Catalog\Model\ProductRepository');
$product = $productRepository->get($item);
//echo $product['foundation_shades']; 

$resource = $objectManager->get('Magento\Framework\App\ResourceConnection');
$connection = $resource->getConnection();
$tableName = $resource->getTableName('eav_attribute_option_swatch');
$sql = "Select * FROM " . $tableName . " WHERE  option_id= ".$product['foundation_shades'];
$result = $connection->fetchAll($sql);
$attr = $product->getResource()->getAttribute('foundation_shades');

?>

 <?php $objectManager = \Magento\Framework\App\ObjectManager::getInstance();

  $listBlock = $objectManager->get('\Magento\Catalog\Block\Product\ListProduct');

  $addToCartUrl =  $listBlock->getAddToCartUrl($product); ?>




<?php  if ($attr->usesSource()) {?>
    <div style="background: <?php echo $result[0]['value'] ;?> no-repeat center;
    background-size: initial;"    class="swatch-option " > 
    <a href=" <?php echo $product->getProductUrl() ;?>">
    </a>
    <span> <?php echo  $optionText = $attr->getSource()->getOptionText($product['foundation_shades']) ?>
    </span>
    </div>
<?php }?>

<div class="qty-buy-col">

 <form data-role="tocart-form" action="<?php echo $addToCartUrl; ?>" method="post"> 
    <div class="quanty-col"><input id="IncDec"  name="qty" type="number" value="1"  data-validate="{"required-number":true,"validate-item-quantity":{"minAllowed":1,"maxAllowed":10000}}"/> <button class="btnAdd" type="button">+</button> <button class="btnMin" type="button">-</button></div>
    <?php echo $block->getBlockHtml('formkey')?>

     <button type="submit" title="Add to Cart" class="action tocart primary buynow-link">

       <span>Buy Now</span>
     </button>
 </form>

</div>


 <?php }  ?>

</div>





<div class="shipped-txt">
<p>*This item cannot be shipped to P.O. Boxes, Alaska, Hawaii, Puerto Rico or Canada.</p>
</div>
</div>
</div>



