<?php 

	$enable = $block->getConfig('enabled');
	if($enable < 1) return ; 
	$itemsDefault = $block->getConfig('itemsDefault');
	$itemsDesktop = $block->getConfig('itemsDesktop');
	$itemsDesktopSmall = $block->getConfig('itemsDesktopSmall');
	$itemsTablet = $block->getConfig('itemsTablet');
	$itemsMobile = $block->getConfig('itemsMobile');
	$title = $block->getConfig('title');
	$items = $block->getConfig('items');
	$speed = $block->getConfig('speed');
	$qty = $block->getConfig('qty');
	$showCart = $block->getConfig('addtocart');
	$showWishlist = $block->getConfig('wishlist');
	$showCompare = $block->getConfig('compare');
	$show_navigation = $block->getConfig('navigation');
	$show_pagination = $block->getConfig('pagination');
	$auto = $block->getConfig('auto');
	$rows = $block->getConfig('row');
	
?>

<div class="front-best-seller"  data-aos="fade-up" data-aos-offset="150"  data-aos-easing="ease-in-sine">
       <div class="container">
        <h2 class="title-main"><?php echo $title;?></h2>
        <div class="bestseller-carousel">
        <div class="owl-carousel owl-theme">
                        
		<?php 
			$saleItems =  $block -> getBestsellerProduct(); 
			
			//echo"<pre>";print_r($saleItems);
			$imageBlock =  $block->getLayout()->createBlock('Magento\Catalog\Block\Product\Image');
			$image = 'new_products_content_widget_grid';
			$type = 'widget-new-grid';
			$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::DEFAULT_VIEW;
			$i=0;
			foreach($saleItems as $_item) { 
					$productImage = $block->getImage($_item, $image);
				?>
						
						<div class="item">
                          <a href="<?php echo $block->getProductUrl($_item) ?>">    	<?php echo $productImage->toHtml() ?></a>
                             
                 <div id="quickview-<?php echo $_item->getId();?>" class="bss-bt-quickview">
				<a class="bss-quickview" data-quickview-url="<?php echo $this->getUrl('');?>/bss_quickview/catalog_product/view/id/<?php echo $_item->getId();?>" href="javascript:void(0);"><span>Quick View </span></a>
				</div>
							 <div class="seller-info">
                           <?php if ($templateType): ?>
								<?php echo $block->getReviewsSummaryHtml($_item, $templateType,true); ?>
							<?php endif; ?>
                                  <div class="seller-name-col">
                                    <a href="<?php echo $block->getProductUrl($_item) ?>" class="title-name"> <?php echo $block->escapeHtml($_item->getName()) ?></a>
                                    <p>
									
									<?php //echo $_item->getShortDescription(); ?>
									
						<?php 
							$short_description = $_item->getShortDescription();
	                      $short_description = preg_replace("/<img[^>]+\>/i", "", $short_description); 
                         if (strlen($short_description) > 100){
                        echo strip_tags(substr($short_description, 0, strpos($short_description,' ',100))).'...';
                           } 
                       else { 
                      echo strip_tags($short_description); 
                           }
                           ?>
									
									</p>
                                  </div>
                                  
								
								  
								  <div class="shopnow-col">
                                      <a href="<?php echo $block->getProductUrl($_item) ?>" class="shopnow-btn">Shop Now</a>
                                  </div>
                              </div>
                          
						  
						  
						  </div>
         
                 

				 
				 <?php }?>
                         
                        
                      </div>
                      <div class="shopbest-col-btm">
                        <a href="<?php echo $this->getBestsellercurl();?>" class="btn btn-primary">Shop Best Sellers</a>
                      </div>
					  
					  
                  </div>
                </div>   
            </div>
            





<script type="text/javascript">
require([
  "jquery",
  "owlcarousel/minjs"
 ], function($,owlCarousel){
	  $('.bestseller-carousel .owl-carousel').owlCarousel({
            loop: true,
            margin: 40,
            nav: true,
            dots: false,
            smartSpeed: 500,
            responsive: {
                0: {
                    items: 1
                },
                568: {
                    items: 2
                },
                768: {
                    items: 3
                },
                992: {
                    items: 4
                }
            }
        });
   /*$("#bestseller_product_slider").owlCarousel({ 
		autoPlay : <?php if($auto) echo 'true'; else echo 'false'; ?>,
		slideSpeed : <?php if($speed) echo $speed; else echo '500'; ?>,
		navigation : <?php if($show_navigation) echo 'true'; else echo 'false'; ?>,
		stopOnHover : true,
		pagination : <?php if($show_pagination) echo 'true'; else echo 'false'; ?>,
		items : <?php if($itemsDefault) echo $itemsDefault; else echo '4'; ?>,
		itemsDesktop : [1199,<?php if($itemsDesktop) echo $itemsDesktop; else echo '4'; ?>],
		itemsDesktopSmall : [980,<?php if($itemsDesktopSmall) echo $itemsDesktopSmall; else echo '3'; ?>],
		itemsTablet: [767,<?php if($itemsTablet) echo $itemsTablet; else echo '2'; ?>],
		itemsMobile : [479,<?php if($itemsMobile) echo $itemsMobile; else echo '1'; ?>],
		addClassActive : true,
		scrollPerPage:false
   });*/
   
});
</script>  


